################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (13.3.rel1)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
C:/Users/lenat/STM32CubeIDE/workspace_1.18.1/STEVAL-25R3916B_V2.1.0/Middlewares/ST/fw_3916/DISCO-STM32L4x6/Src/ce.c \
C:/Users/lenat/STM32CubeIDE/workspace_1.18.1/STEVAL-25R3916B_V2.1.0/Middlewares/ST/fw_3916/DISCO-STM32L4x6/Src/dispatcher.c \
C:/Users/lenat/STM32CubeIDE/workspace_1.18.1/STEVAL-25R3916B_V2.1.0/Middlewares/ST/fw_3916/DISCO-STM32L4x6/Src/felica.c \
C:/Users/lenat/STM32CubeIDE/workspace_1.18.1/STEVAL-25R3916B_V2.1.0/Middlewares/ST/fw_3916/DISCO-STM32L4x6/Src/iso14443_common.c \
C:/Users/lenat/STM32CubeIDE/workspace_1.18.1/STEVAL-25R3916B_V2.1.0/Middlewares/ST/fw_3916/DISCO-STM32L4x6/Src/iso14443a.c \
C:/Users/lenat/STM32CubeIDE/workspace_1.18.1/STEVAL-25R3916B_V2.1.0/Middlewares/ST/fw_3916/DISCO-STM32L4x6/Src/iso14443b.c \
C:/Users/lenat/STM32CubeIDE/workspace_1.18.1/STEVAL-25R3916B_V2.1.0/Middlewares/ST/fw_3916/DISCO-STM32L4x6/Src/iso14443b_st25tb.c \
C:/Users/lenat/STM32CubeIDE/workspace_1.18.1/STEVAL-25R3916B_V2.1.0/Middlewares/ST/fw_3916/DISCO-STM32L4x6/Src/iso15693_3.c \
C:/Users/lenat/STM32CubeIDE/workspace_1.18.1/STEVAL-25R3916B_V2.1.0/Middlewares/ST/fw_3916/DISCO-STM32L4x6/Src/kovio.c \
C:/Users/lenat/STM32CubeIDE/workspace_1.18.1/STEVAL-25R3916B_V2.1.0/Middlewares/ST/fw_3916/DISCO-STM32L4x6/Src/led.c \
C:/Users/lenat/STM32CubeIDE/workspace_1.18.1/STEVAL-25R3916B_V2.1.0/Middlewares/ST/fw_3916/DISCO-STM32L4x6/Src/nfc.c \
C:/Users/lenat/STM32CubeIDE/workspace_1.18.1/STEVAL-25R3916B_V2.1.0/Middlewares/ST/fw_3916/DISCO-STM32L4x6/Src/t2t.c \
C:/Users/lenat/STM32CubeIDE/workspace_1.18.1/STEVAL-25R3916B_V2.1.0/Middlewares/ST/fw_3916/DISCO-STM32L4x6/Src/topaz.c \
C:/Users/lenat/STM32CubeIDE/workspace_1.18.1/STEVAL-25R3916B_V2.1.0/Middlewares/ST/fw_3916/DISCO-STM32L4x6/Src/tuneAntenna.c 

OBJS += \
./Middleware/fw_3916/ce.o \
./Middleware/fw_3916/dispatcher.o \
./Middleware/fw_3916/felica.o \
./Middleware/fw_3916/iso14443_common.o \
./Middleware/fw_3916/iso14443a.o \
./Middleware/fw_3916/iso14443b.o \
./Middleware/fw_3916/iso14443b_st25tb.o \
./Middleware/fw_3916/iso15693_3.o \
./Middleware/fw_3916/kovio.o \
./Middleware/fw_3916/led.o \
./Middleware/fw_3916/nfc.o \
./Middleware/fw_3916/t2t.o \
./Middleware/fw_3916/topaz.o \
./Middleware/fw_3916/tuneAntenna.o 

C_DEPS += \
./Middleware/fw_3916/ce.d \
./Middleware/fw_3916/dispatcher.d \
./Middleware/fw_3916/felica.d \
./Middleware/fw_3916/iso14443_common.d \
./Middleware/fw_3916/iso14443a.d \
./Middleware/fw_3916/iso14443b.d \
./Middleware/fw_3916/iso14443b_st25tb.d \
./Middleware/fw_3916/iso15693_3.d \
./Middleware/fw_3916/kovio.d \
./Middleware/fw_3916/led.d \
./Middleware/fw_3916/nfc.d \
./Middleware/fw_3916/t2t.d \
./Middleware/fw_3916/topaz.d \
./Middleware/fw_3916/tuneAntenna.d 


# Each subdirectory must supply rules for building sources it contributes
Middleware/fw_3916/ce.o: C:/Users/lenat/STM32CubeIDE/workspace_1.18.1/STEVAL-25R3916B_V2.1.0/Middlewares/ST/fw_3916/DISCO-STM32L4x6/Src/ce.c Middleware/fw_3916/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu99 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32L476xx -DUSE_LCD -DMENU_DEMO_CENTER_ICONS=1 -DUSE_LOGGER=1 -DUSE_MB1749_A=1 -DST25R3916B -DUSE_M25R16B -DUSE_JOYSTICKONLY '-DANALOG_CONFIG_OFFSET=(0x000E1000U)' -c -I../../Inc -I../../Picture -I../../../../../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../../../../../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -I../../../../../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../../../../../Drivers/CMSIS/Include -I../../../../../../Drivers/BSP/ST25-Discovery -I../../../../../../Drivers/BSP/Components/Common -I../../../../../../Drivers/BSP/Components/stmpe811 -I../../../../../../Drivers/BSP/Components/ad5112 -I../../../../../../Drivers/BSP/Components/ili9341_cube -I../../../../../../Middlewares/Third_Party/LibJPEG/include -I../../../../../../Middlewares/ST/menu_demo -I../../../../../../Middlewares/ST/NDEF/include/message -I../../../../../../Middlewares/ST/NDEF/include/poller -I../../../../../../Middlewares/ST/RFAL/include -I../../../../../../Middlewares/ST/RFAL/source -I../../../../../../Middlewares/ST/RFAL/source/st25r3916 -I../../../../../../Middlewares/ST/Reader_common/firmware/STM/utils/Inc -I../../../../../../Middlewares/ST/Reader_common/firmware/STM/STM32/Inc -I../../../../../../Middlewares/ST/fw_3916/DISCO-STM32L4x6/Inc -I../../../../../../Middlewares/ST/p2p -I../../../../../../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I../../../../../../Middlewares/ST/STM32_USB_Device_Library/Class/CustomHID/Inc -I../../../../../../Middlewares/ST/STM32_USB_Device_Library/Class/HID/Inc -I../../../../../../Middlewares/Third_Party/LibJPEG/include -I../../../../../../Utilities/Fonts -O1 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middleware/fw_3916/dispatcher.o: C:/Users/lenat/STM32CubeIDE/workspace_1.18.1/STEVAL-25R3916B_V2.1.0/Middlewares/ST/fw_3916/DISCO-STM32L4x6/Src/dispatcher.c Middleware/fw_3916/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu99 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32L476xx -DUSE_LCD -DMENU_DEMO_CENTER_ICONS=1 -DUSE_LOGGER=1 -DUSE_MB1749_A=1 -DST25R3916B -DUSE_M25R16B -DUSE_JOYSTICKONLY '-DANALOG_CONFIG_OFFSET=(0x000E1000U)' -c -I../../Inc -I../../Picture -I../../../../../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../../../../../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -I../../../../../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../../../../../Drivers/CMSIS/Include -I../../../../../../Drivers/BSP/ST25-Discovery -I../../../../../../Drivers/BSP/Components/Common -I../../../../../../Drivers/BSP/Components/stmpe811 -I../../../../../../Drivers/BSP/Components/ad5112 -I../../../../../../Drivers/BSP/Components/ili9341_cube -I../../../../../../Middlewares/Third_Party/LibJPEG/include -I../../../../../../Middlewares/ST/menu_demo -I../../../../../../Middlewares/ST/NDEF/include/message -I../../../../../../Middlewares/ST/NDEF/include/poller -I../../../../../../Middlewares/ST/RFAL/include -I../../../../../../Middlewares/ST/RFAL/source -I../../../../../../Middlewares/ST/RFAL/source/st25r3916 -I../../../../../../Middlewares/ST/Reader_common/firmware/STM/utils/Inc -I../../../../../../Middlewares/ST/Reader_common/firmware/STM/STM32/Inc -I../../../../../../Middlewares/ST/fw_3916/DISCO-STM32L4x6/Inc -I../../../../../../Middlewares/ST/p2p -I../../../../../../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I../../../../../../Middlewares/ST/STM32_USB_Device_Library/Class/CustomHID/Inc -I../../../../../../Middlewares/ST/STM32_USB_Device_Library/Class/HID/Inc -I../../../../../../Middlewares/Third_Party/LibJPEG/include -I../../../../../../Utilities/Fonts -O1 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middleware/fw_3916/felica.o: C:/Users/lenat/STM32CubeIDE/workspace_1.18.1/STEVAL-25R3916B_V2.1.0/Middlewares/ST/fw_3916/DISCO-STM32L4x6/Src/felica.c Middleware/fw_3916/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu99 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32L476xx -DUSE_LCD -DMENU_DEMO_CENTER_ICONS=1 -DUSE_LOGGER=1 -DUSE_MB1749_A=1 -DST25R3916B -DUSE_M25R16B -DUSE_JOYSTICKONLY '-DANALOG_CONFIG_OFFSET=(0x000E1000U)' -c -I../../Inc -I../../Picture -I../../../../../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../../../../../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -I../../../../../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../../../../../Drivers/CMSIS/Include -I../../../../../../Drivers/BSP/ST25-Discovery -I../../../../../../Drivers/BSP/Components/Common -I../../../../../../Drivers/BSP/Components/stmpe811 -I../../../../../../Drivers/BSP/Components/ad5112 -I../../../../../../Drivers/BSP/Components/ili9341_cube -I../../../../../../Middlewares/Third_Party/LibJPEG/include -I../../../../../../Middlewares/ST/menu_demo -I../../../../../../Middlewares/ST/NDEF/include/message -I../../../../../../Middlewares/ST/NDEF/include/poller -I../../../../../../Middlewares/ST/RFAL/include -I../../../../../../Middlewares/ST/RFAL/source -I../../../../../../Middlewares/ST/RFAL/source/st25r3916 -I../../../../../../Middlewares/ST/Reader_common/firmware/STM/utils/Inc -I../../../../../../Middlewares/ST/Reader_common/firmware/STM/STM32/Inc -I../../../../../../Middlewares/ST/fw_3916/DISCO-STM32L4x6/Inc -I../../../../../../Middlewares/ST/p2p -I../../../../../../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I../../../../../../Middlewares/ST/STM32_USB_Device_Library/Class/CustomHID/Inc -I../../../../../../Middlewares/ST/STM32_USB_Device_Library/Class/HID/Inc -I../../../../../../Middlewares/Third_Party/LibJPEG/include -I../../../../../../Utilities/Fonts -O1 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middleware/fw_3916/iso14443_common.o: C:/Users/lenat/STM32CubeIDE/workspace_1.18.1/STEVAL-25R3916B_V2.1.0/Middlewares/ST/fw_3916/DISCO-STM32L4x6/Src/iso14443_common.c Middleware/fw_3916/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu99 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32L476xx -DUSE_LCD -DMENU_DEMO_CENTER_ICONS=1 -DUSE_LOGGER=1 -DUSE_MB1749_A=1 -DST25R3916B -DUSE_M25R16B -DUSE_JOYSTICKONLY '-DANALOG_CONFIG_OFFSET=(0x000E1000U)' -c -I../../Inc -I../../Picture -I../../../../../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../../../../../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -I../../../../../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../../../../../Drivers/CMSIS/Include -I../../../../../../Drivers/BSP/ST25-Discovery -I../../../../../../Drivers/BSP/Components/Common -I../../../../../../Drivers/BSP/Components/stmpe811 -I../../../../../../Drivers/BSP/Components/ad5112 -I../../../../../../Drivers/BSP/Components/ili9341_cube -I../../../../../../Middlewares/Third_Party/LibJPEG/include -I../../../../../../Middlewares/ST/menu_demo -I../../../../../../Middlewares/ST/NDEF/include/message -I../../../../../../Middlewares/ST/NDEF/include/poller -I../../../../../../Middlewares/ST/RFAL/include -I../../../../../../Middlewares/ST/RFAL/source -I../../../../../../Middlewares/ST/RFAL/source/st25r3916 -I../../../../../../Middlewares/ST/Reader_common/firmware/STM/utils/Inc -I../../../../../../Middlewares/ST/Reader_common/firmware/STM/STM32/Inc -I../../../../../../Middlewares/ST/fw_3916/DISCO-STM32L4x6/Inc -I../../../../../../Middlewares/ST/p2p -I../../../../../../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I../../../../../../Middlewares/ST/STM32_USB_Device_Library/Class/CustomHID/Inc -I../../../../../../Middlewares/ST/STM32_USB_Device_Library/Class/HID/Inc -I../../../../../../Middlewares/Third_Party/LibJPEG/include -I../../../../../../Utilities/Fonts -O1 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middleware/fw_3916/iso14443a.o: C:/Users/lenat/STM32CubeIDE/workspace_1.18.1/STEVAL-25R3916B_V2.1.0/Middlewares/ST/fw_3916/DISCO-STM32L4x6/Src/iso14443a.c Middleware/fw_3916/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu99 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32L476xx -DUSE_LCD -DMENU_DEMO_CENTER_ICONS=1 -DUSE_LOGGER=1 -DUSE_MB1749_A=1 -DST25R3916B -DUSE_M25R16B -DUSE_JOYSTICKONLY '-DANALOG_CONFIG_OFFSET=(0x000E1000U)' -c -I../../Inc -I../../Picture -I../../../../../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../../../../../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -I../../../../../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../../../../../Drivers/CMSIS/Include -I../../../../../../Drivers/BSP/ST25-Discovery -I../../../../../../Drivers/BSP/Components/Common -I../../../../../../Drivers/BSP/Components/stmpe811 -I../../../../../../Drivers/BSP/Components/ad5112 -I../../../../../../Drivers/BSP/Components/ili9341_cube -I../../../../../../Middlewares/Third_Party/LibJPEG/include -I../../../../../../Middlewares/ST/menu_demo -I../../../../../../Middlewares/ST/NDEF/include/message -I../../../../../../Middlewares/ST/NDEF/include/poller -I../../../../../../Middlewares/ST/RFAL/include -I../../../../../../Middlewares/ST/RFAL/source -I../../../../../../Middlewares/ST/RFAL/source/st25r3916 -I../../../../../../Middlewares/ST/Reader_common/firmware/STM/utils/Inc -I../../../../../../Middlewares/ST/Reader_common/firmware/STM/STM32/Inc -I../../../../../../Middlewares/ST/fw_3916/DISCO-STM32L4x6/Inc -I../../../../../../Middlewares/ST/p2p -I../../../../../../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I../../../../../../Middlewares/ST/STM32_USB_Device_Library/Class/CustomHID/Inc -I../../../../../../Middlewares/ST/STM32_USB_Device_Library/Class/HID/Inc -I../../../../../../Middlewares/Third_Party/LibJPEG/include -I../../../../../../Utilities/Fonts -O1 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middleware/fw_3916/iso14443b.o: C:/Users/lenat/STM32CubeIDE/workspace_1.18.1/STEVAL-25R3916B_V2.1.0/Middlewares/ST/fw_3916/DISCO-STM32L4x6/Src/iso14443b.c Middleware/fw_3916/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu99 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32L476xx -DUSE_LCD -DMENU_DEMO_CENTER_ICONS=1 -DUSE_LOGGER=1 -DUSE_MB1749_A=1 -DST25R3916B -DUSE_M25R16B -DUSE_JOYSTICKONLY '-DANALOG_CONFIG_OFFSET=(0x000E1000U)' -c -I../../Inc -I../../Picture -I../../../../../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../../../../../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -I../../../../../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../../../../../Drivers/CMSIS/Include -I../../../../../../Drivers/BSP/ST25-Discovery -I../../../../../../Drivers/BSP/Components/Common -I../../../../../../Drivers/BSP/Components/stmpe811 -I../../../../../../Drivers/BSP/Components/ad5112 -I../../../../../../Drivers/BSP/Components/ili9341_cube -I../../../../../../Middlewares/Third_Party/LibJPEG/include -I../../../../../../Middlewares/ST/menu_demo -I../../../../../../Middlewares/ST/NDEF/include/message -I../../../../../../Middlewares/ST/NDEF/include/poller -I../../../../../../Middlewares/ST/RFAL/include -I../../../../../../Middlewares/ST/RFAL/source -I../../../../../../Middlewares/ST/RFAL/source/st25r3916 -I../../../../../../Middlewares/ST/Reader_common/firmware/STM/utils/Inc -I../../../../../../Middlewares/ST/Reader_common/firmware/STM/STM32/Inc -I../../../../../../Middlewares/ST/fw_3916/DISCO-STM32L4x6/Inc -I../../../../../../Middlewares/ST/p2p -I../../../../../../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I../../../../../../Middlewares/ST/STM32_USB_Device_Library/Class/CustomHID/Inc -I../../../../../../Middlewares/ST/STM32_USB_Device_Library/Class/HID/Inc -I../../../../../../Middlewares/Third_Party/LibJPEG/include -I../../../../../../Utilities/Fonts -O1 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middleware/fw_3916/iso14443b_st25tb.o: C:/Users/lenat/STM32CubeIDE/workspace_1.18.1/STEVAL-25R3916B_V2.1.0/Middlewares/ST/fw_3916/DISCO-STM32L4x6/Src/iso14443b_st25tb.c Middleware/fw_3916/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu99 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32L476xx -DUSE_LCD -DMENU_DEMO_CENTER_ICONS=1 -DUSE_LOGGER=1 -DUSE_MB1749_A=1 -DST25R3916B -DUSE_M25R16B -DUSE_JOYSTICKONLY '-DANALOG_CONFIG_OFFSET=(0x000E1000U)' -c -I../../Inc -I../../Picture -I../../../../../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../../../../../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -I../../../../../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../../../../../Drivers/CMSIS/Include -I../../../../../../Drivers/BSP/ST25-Discovery -I../../../../../../Drivers/BSP/Components/Common -I../../../../../../Drivers/BSP/Components/stmpe811 -I../../../../../../Drivers/BSP/Components/ad5112 -I../../../../../../Drivers/BSP/Components/ili9341_cube -I../../../../../../Middlewares/Third_Party/LibJPEG/include -I../../../../../../Middlewares/ST/menu_demo -I../../../../../../Middlewares/ST/NDEF/include/message -I../../../../../../Middlewares/ST/NDEF/include/poller -I../../../../../../Middlewares/ST/RFAL/include -I../../../../../../Middlewares/ST/RFAL/source -I../../../../../../Middlewares/ST/RFAL/source/st25r3916 -I../../../../../../Middlewares/ST/Reader_common/firmware/STM/utils/Inc -I../../../../../../Middlewares/ST/Reader_common/firmware/STM/STM32/Inc -I../../../../../../Middlewares/ST/fw_3916/DISCO-STM32L4x6/Inc -I../../../../../../Middlewares/ST/p2p -I../../../../../../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I../../../../../../Middlewares/ST/STM32_USB_Device_Library/Class/CustomHID/Inc -I../../../../../../Middlewares/ST/STM32_USB_Device_Library/Class/HID/Inc -I../../../../../../Middlewares/Third_Party/LibJPEG/include -I../../../../../../Utilities/Fonts -O1 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middleware/fw_3916/iso15693_3.o: C:/Users/lenat/STM32CubeIDE/workspace_1.18.1/STEVAL-25R3916B_V2.1.0/Middlewares/ST/fw_3916/DISCO-STM32L4x6/Src/iso15693_3.c Middleware/fw_3916/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu99 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32L476xx -DUSE_LCD -DMENU_DEMO_CENTER_ICONS=1 -DUSE_LOGGER=1 -DUSE_MB1749_A=1 -DST25R3916B -DUSE_M25R16B -DUSE_JOYSTICKONLY '-DANALOG_CONFIG_OFFSET=(0x000E1000U)' -c -I../../Inc -I../../Picture -I../../../../../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../../../../../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -I../../../../../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../../../../../Drivers/CMSIS/Include -I../../../../../../Drivers/BSP/ST25-Discovery -I../../../../../../Drivers/BSP/Components/Common -I../../../../../../Drivers/BSP/Components/stmpe811 -I../../../../../../Drivers/BSP/Components/ad5112 -I../../../../../../Drivers/BSP/Components/ili9341_cube -I../../../../../../Middlewares/Third_Party/LibJPEG/include -I../../../../../../Middlewares/ST/menu_demo -I../../../../../../Middlewares/ST/NDEF/include/message -I../../../../../../Middlewares/ST/NDEF/include/poller -I../../../../../../Middlewares/ST/RFAL/include -I../../../../../../Middlewares/ST/RFAL/source -I../../../../../../Middlewares/ST/RFAL/source/st25r3916 -I../../../../../../Middlewares/ST/Reader_common/firmware/STM/utils/Inc -I../../../../../../Middlewares/ST/Reader_common/firmware/STM/STM32/Inc -I../../../../../../Middlewares/ST/fw_3916/DISCO-STM32L4x6/Inc -I../../../../../../Middlewares/ST/p2p -I../../../../../../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I../../../../../../Middlewares/ST/STM32_USB_Device_Library/Class/CustomHID/Inc -I../../../../../../Middlewares/ST/STM32_USB_Device_Library/Class/HID/Inc -I../../../../../../Middlewares/Third_Party/LibJPEG/include -I../../../../../../Utilities/Fonts -O1 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middleware/fw_3916/kovio.o: C:/Users/lenat/STM32CubeIDE/workspace_1.18.1/STEVAL-25R3916B_V2.1.0/Middlewares/ST/fw_3916/DISCO-STM32L4x6/Src/kovio.c Middleware/fw_3916/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu99 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32L476xx -DUSE_LCD -DMENU_DEMO_CENTER_ICONS=1 -DUSE_LOGGER=1 -DUSE_MB1749_A=1 -DST25R3916B -DUSE_M25R16B -DUSE_JOYSTICKONLY '-DANALOG_CONFIG_OFFSET=(0x000E1000U)' -c -I../../Inc -I../../Picture -I../../../../../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../../../../../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -I../../../../../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../../../../../Drivers/CMSIS/Include -I../../../../../../Drivers/BSP/ST25-Discovery -I../../../../../../Drivers/BSP/Components/Common -I../../../../../../Drivers/BSP/Components/stmpe811 -I../../../../../../Drivers/BSP/Components/ad5112 -I../../../../../../Drivers/BSP/Components/ili9341_cube -I../../../../../../Middlewares/Third_Party/LibJPEG/include -I../../../../../../Middlewares/ST/menu_demo -I../../../../../../Middlewares/ST/NDEF/include/message -I../../../../../../Middlewares/ST/NDEF/include/poller -I../../../../../../Middlewares/ST/RFAL/include -I../../../../../../Middlewares/ST/RFAL/source -I../../../../../../Middlewares/ST/RFAL/source/st25r3916 -I../../../../../../Middlewares/ST/Reader_common/firmware/STM/utils/Inc -I../../../../../../Middlewares/ST/Reader_common/firmware/STM/STM32/Inc -I../../../../../../Middlewares/ST/fw_3916/DISCO-STM32L4x6/Inc -I../../../../../../Middlewares/ST/p2p -I../../../../../../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I../../../../../../Middlewares/ST/STM32_USB_Device_Library/Class/CustomHID/Inc -I../../../../../../Middlewares/ST/STM32_USB_Device_Library/Class/HID/Inc -I../../../../../../Middlewares/Third_Party/LibJPEG/include -I../../../../../../Utilities/Fonts -O1 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middleware/fw_3916/led.o: C:/Users/lenat/STM32CubeIDE/workspace_1.18.1/STEVAL-25R3916B_V2.1.0/Middlewares/ST/fw_3916/DISCO-STM32L4x6/Src/led.c Middleware/fw_3916/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu99 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32L476xx -DUSE_LCD -DMENU_DEMO_CENTER_ICONS=1 -DUSE_LOGGER=1 -DUSE_MB1749_A=1 -DST25R3916B -DUSE_M25R16B -DUSE_JOYSTICKONLY '-DANALOG_CONFIG_OFFSET=(0x000E1000U)' -c -I../../Inc -I../../Picture -I../../../../../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../../../../../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -I../../../../../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../../../../../Drivers/CMSIS/Include -I../../../../../../Drivers/BSP/ST25-Discovery -I../../../../../../Drivers/BSP/Components/Common -I../../../../../../Drivers/BSP/Components/stmpe811 -I../../../../../../Drivers/BSP/Components/ad5112 -I../../../../../../Drivers/BSP/Components/ili9341_cube -I../../../../../../Middlewares/Third_Party/LibJPEG/include -I../../../../../../Middlewares/ST/menu_demo -I../../../../../../Middlewares/ST/NDEF/include/message -I../../../../../../Middlewares/ST/NDEF/include/poller -I../../../../../../Middlewares/ST/RFAL/include -I../../../../../../Middlewares/ST/RFAL/source -I../../../../../../Middlewares/ST/RFAL/source/st25r3916 -I../../../../../../Middlewares/ST/Reader_common/firmware/STM/utils/Inc -I../../../../../../Middlewares/ST/Reader_common/firmware/STM/STM32/Inc -I../../../../../../Middlewares/ST/fw_3916/DISCO-STM32L4x6/Inc -I../../../../../../Middlewares/ST/p2p -I../../../../../../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I../../../../../../Middlewares/ST/STM32_USB_Device_Library/Class/CustomHID/Inc -I../../../../../../Middlewares/ST/STM32_USB_Device_Library/Class/HID/Inc -I../../../../../../Middlewares/Third_Party/LibJPEG/include -I../../../../../../Utilities/Fonts -O1 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middleware/fw_3916/nfc.o: C:/Users/lenat/STM32CubeIDE/workspace_1.18.1/STEVAL-25R3916B_V2.1.0/Middlewares/ST/fw_3916/DISCO-STM32L4x6/Src/nfc.c Middleware/fw_3916/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu99 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32L476xx -DUSE_LCD -DMENU_DEMO_CENTER_ICONS=1 -DUSE_LOGGER=1 -DUSE_MB1749_A=1 -DST25R3916B -DUSE_M25R16B -DUSE_JOYSTICKONLY '-DANALOG_CONFIG_OFFSET=(0x000E1000U)' -c -I../../Inc -I../../Picture -I../../../../../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../../../../../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -I../../../../../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../../../../../Drivers/CMSIS/Include -I../../../../../../Drivers/BSP/ST25-Discovery -I../../../../../../Drivers/BSP/Components/Common -I../../../../../../Drivers/BSP/Components/stmpe811 -I../../../../../../Drivers/BSP/Components/ad5112 -I../../../../../../Drivers/BSP/Components/ili9341_cube -I../../../../../../Middlewares/Third_Party/LibJPEG/include -I../../../../../../Middlewares/ST/menu_demo -I../../../../../../Middlewares/ST/NDEF/include/message -I../../../../../../Middlewares/ST/NDEF/include/poller -I../../../../../../Middlewares/ST/RFAL/include -I../../../../../../Middlewares/ST/RFAL/source -I../../../../../../Middlewares/ST/RFAL/source/st25r3916 -I../../../../../../Middlewares/ST/Reader_common/firmware/STM/utils/Inc -I../../../../../../Middlewares/ST/Reader_common/firmware/STM/STM32/Inc -I../../../../../../Middlewares/ST/fw_3916/DISCO-STM32L4x6/Inc -I../../../../../../Middlewares/ST/p2p -I../../../../../../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I../../../../../../Middlewares/ST/STM32_USB_Device_Library/Class/CustomHID/Inc -I../../../../../../Middlewares/ST/STM32_USB_Device_Library/Class/HID/Inc -I../../../../../../Middlewares/Third_Party/LibJPEG/include -I../../../../../../Utilities/Fonts -O1 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middleware/fw_3916/t2t.o: C:/Users/lenat/STM32CubeIDE/workspace_1.18.1/STEVAL-25R3916B_V2.1.0/Middlewares/ST/fw_3916/DISCO-STM32L4x6/Src/t2t.c Middleware/fw_3916/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu99 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32L476xx -DUSE_LCD -DMENU_DEMO_CENTER_ICONS=1 -DUSE_LOGGER=1 -DUSE_MB1749_A=1 -DST25R3916B -DUSE_M25R16B -DUSE_JOYSTICKONLY '-DANALOG_CONFIG_OFFSET=(0x000E1000U)' -c -I../../Inc -I../../Picture -I../../../../../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../../../../../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -I../../../../../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../../../../../Drivers/CMSIS/Include -I../../../../../../Drivers/BSP/ST25-Discovery -I../../../../../../Drivers/BSP/Components/Common -I../../../../../../Drivers/BSP/Components/stmpe811 -I../../../../../../Drivers/BSP/Components/ad5112 -I../../../../../../Drivers/BSP/Components/ili9341_cube -I../../../../../../Middlewares/Third_Party/LibJPEG/include -I../../../../../../Middlewares/ST/menu_demo -I../../../../../../Middlewares/ST/NDEF/include/message -I../../../../../../Middlewares/ST/NDEF/include/poller -I../../../../../../Middlewares/ST/RFAL/include -I../../../../../../Middlewares/ST/RFAL/source -I../../../../../../Middlewares/ST/RFAL/source/st25r3916 -I../../../../../../Middlewares/ST/Reader_common/firmware/STM/utils/Inc -I../../../../../../Middlewares/ST/Reader_common/firmware/STM/STM32/Inc -I../../../../../../Middlewares/ST/fw_3916/DISCO-STM32L4x6/Inc -I../../../../../../Middlewares/ST/p2p -I../../../../../../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I../../../../../../Middlewares/ST/STM32_USB_Device_Library/Class/CustomHID/Inc -I../../../../../../Middlewares/ST/STM32_USB_Device_Library/Class/HID/Inc -I../../../../../../Middlewares/Third_Party/LibJPEG/include -I../../../../../../Utilities/Fonts -O1 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middleware/fw_3916/topaz.o: C:/Users/lenat/STM32CubeIDE/workspace_1.18.1/STEVAL-25R3916B_V2.1.0/Middlewares/ST/fw_3916/DISCO-STM32L4x6/Src/topaz.c Middleware/fw_3916/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu99 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32L476xx -DUSE_LCD -DMENU_DEMO_CENTER_ICONS=1 -DUSE_LOGGER=1 -DUSE_MB1749_A=1 -DST25R3916B -DUSE_M25R16B -DUSE_JOYSTICKONLY '-DANALOG_CONFIG_OFFSET=(0x000E1000U)' -c -I../../Inc -I../../Picture -I../../../../../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../../../../../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -I../../../../../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../../../../../Drivers/CMSIS/Include -I../../../../../../Drivers/BSP/ST25-Discovery -I../../../../../../Drivers/BSP/Components/Common -I../../../../../../Drivers/BSP/Components/stmpe811 -I../../../../../../Drivers/BSP/Components/ad5112 -I../../../../../../Drivers/BSP/Components/ili9341_cube -I../../../../../../Middlewares/Third_Party/LibJPEG/include -I../../../../../../Middlewares/ST/menu_demo -I../../../../../../Middlewares/ST/NDEF/include/message -I../../../../../../Middlewares/ST/NDEF/include/poller -I../../../../../../Middlewares/ST/RFAL/include -I../../../../../../Middlewares/ST/RFAL/source -I../../../../../../Middlewares/ST/RFAL/source/st25r3916 -I../../../../../../Middlewares/ST/Reader_common/firmware/STM/utils/Inc -I../../../../../../Middlewares/ST/Reader_common/firmware/STM/STM32/Inc -I../../../../../../Middlewares/ST/fw_3916/DISCO-STM32L4x6/Inc -I../../../../../../Middlewares/ST/p2p -I../../../../../../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I../../../../../../Middlewares/ST/STM32_USB_Device_Library/Class/CustomHID/Inc -I../../../../../../Middlewares/ST/STM32_USB_Device_Library/Class/HID/Inc -I../../../../../../Middlewares/Third_Party/LibJPEG/include -I../../../../../../Utilities/Fonts -O1 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middleware/fw_3916/tuneAntenna.o: C:/Users/lenat/STM32CubeIDE/workspace_1.18.1/STEVAL-25R3916B_V2.1.0/Middlewares/ST/fw_3916/DISCO-STM32L4x6/Src/tuneAntenna.c Middleware/fw_3916/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu99 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32L476xx -DUSE_LCD -DMENU_DEMO_CENTER_ICONS=1 -DUSE_LOGGER=1 -DUSE_MB1749_A=1 -DST25R3916B -DUSE_M25R16B -DUSE_JOYSTICKONLY '-DANALOG_CONFIG_OFFSET=(0x000E1000U)' -c -I../../Inc -I../../Picture -I../../../../../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../../../../../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -I../../../../../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../../../../../Drivers/CMSIS/Include -I../../../../../../Drivers/BSP/ST25-Discovery -I../../../../../../Drivers/BSP/Components/Common -I../../../../../../Drivers/BSP/Components/stmpe811 -I../../../../../../Drivers/BSP/Components/ad5112 -I../../../../../../Drivers/BSP/Components/ili9341_cube -I../../../../../../Middlewares/Third_Party/LibJPEG/include -I../../../../../../Middlewares/ST/menu_demo -I../../../../../../Middlewares/ST/NDEF/include/message -I../../../../../../Middlewares/ST/NDEF/include/poller -I../../../../../../Middlewares/ST/RFAL/include -I../../../../../../Middlewares/ST/RFAL/source -I../../../../../../Middlewares/ST/RFAL/source/st25r3916 -I../../../../../../Middlewares/ST/Reader_common/firmware/STM/utils/Inc -I../../../../../../Middlewares/ST/Reader_common/firmware/STM/STM32/Inc -I../../../../../../Middlewares/ST/fw_3916/DISCO-STM32L4x6/Inc -I../../../../../../Middlewares/ST/p2p -I../../../../../../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I../../../../../../Middlewares/ST/STM32_USB_Device_Library/Class/CustomHID/Inc -I../../../../../../Middlewares/ST/STM32_USB_Device_Library/Class/HID/Inc -I../../../../../../Middlewares/Third_Party/LibJPEG/include -I../../../../../../Utilities/Fonts -O1 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"

clean: clean-Middleware-2f-fw_3916

clean-Middleware-2f-fw_3916:
	-$(RM) ./Middleware/fw_3916/ce.cyclo ./Middleware/fw_3916/ce.d ./Middleware/fw_3916/ce.o ./Middleware/fw_3916/ce.su ./Middleware/fw_3916/dispatcher.cyclo ./Middleware/fw_3916/dispatcher.d ./Middleware/fw_3916/dispatcher.o ./Middleware/fw_3916/dispatcher.su ./Middleware/fw_3916/felica.cyclo ./Middleware/fw_3916/felica.d ./Middleware/fw_3916/felica.o ./Middleware/fw_3916/felica.su ./Middleware/fw_3916/iso14443_common.cyclo ./Middleware/fw_3916/iso14443_common.d ./Middleware/fw_3916/iso14443_common.o ./Middleware/fw_3916/iso14443_common.su ./Middleware/fw_3916/iso14443a.cyclo ./Middleware/fw_3916/iso14443a.d ./Middleware/fw_3916/iso14443a.o ./Middleware/fw_3916/iso14443a.su ./Middleware/fw_3916/iso14443b.cyclo ./Middleware/fw_3916/iso14443b.d ./Middleware/fw_3916/iso14443b.o ./Middleware/fw_3916/iso14443b.su ./Middleware/fw_3916/iso14443b_st25tb.cyclo ./Middleware/fw_3916/iso14443b_st25tb.d ./Middleware/fw_3916/iso14443b_st25tb.o ./Middleware/fw_3916/iso14443b_st25tb.su ./Middleware/fw_3916/iso15693_3.cyclo ./Middleware/fw_3916/iso15693_3.d ./Middleware/fw_3916/iso15693_3.o ./Middleware/fw_3916/iso15693_3.su ./Middleware/fw_3916/kovio.cyclo ./Middleware/fw_3916/kovio.d ./Middleware/fw_3916/kovio.o ./Middleware/fw_3916/kovio.su ./Middleware/fw_3916/led.cyclo ./Middleware/fw_3916/led.d ./Middleware/fw_3916/led.o ./Middleware/fw_3916/led.su ./Middleware/fw_3916/nfc.cyclo ./Middleware/fw_3916/nfc.d ./Middleware/fw_3916/nfc.o ./Middleware/fw_3916/nfc.su ./Middleware/fw_3916/t2t.cyclo ./Middleware/fw_3916/t2t.d ./Middleware/fw_3916/t2t.o ./Middleware/fw_3916/t2t.su ./Middleware/fw_3916/topaz.cyclo ./Middleware/fw_3916/topaz.d ./Middleware/fw_3916/topaz.o ./Middleware/fw_3916/topaz.su ./Middleware/fw_3916/tuneAntenna.cyclo ./Middleware/fw_3916/tuneAntenna.d ./Middleware/fw_3916/tuneAntenna.o ./Middleware/fw_3916/tuneAntenna.su

.PHONY: clean-Middleware-2f-fw_3916

